services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    env_file: 
      - ./backend/.env
    depends_on:
      - db
  
  db:
    image: postgres:17-bookworm
    container_name: db
    ports:
      - 5432:5432
    env_file:
      - ./databases/postgres/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
