# Generated by Django 5.1.4 on 2024-12-11 10:20

import django.db.models.deletion
from django.db import migrations, models


def set_unique_teacher_ids(apps, schema_editor):
    Course = apps.get_model('student', 'Course')
    Teacher = apps.get_model('student', 'Teacher')

    # Create default teachers width unique IDs for existing courses
    for index, course in enumerate(Course.objects.all(), start=1):
        # Create a dummy teacher for each course
        teacher = Teacher.objects.create(
            first_name=f"Default{index}",
            last_name=f"Teacher{index}",
            email=f"default_teacher_{index}@example.com",
            gender='O',
            hire_data='2024-12-11',
            is_active=True
        )
        course.teacher = teacher
        course.save()

class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_course_student_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('hire_data', models.DateField()),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='student.teacher'),
            preserve_default=False,
        ),
        migrations.RunPython(set_unique_teacher_ids),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='student.teacher', null=False),
        )
    ]
